### ISSUE TITLE
Still depends on 3.24 runtime

### ISSUE THREAD

**Issue by afranke** [flathub/org.gnome.Recipes#9]
Next builds should depend on a more recent version of the GNOME platform runtime.

**Comment by afranke** [comment]
A bit of background: I needed space on my hard drive to upgrade to Fedora 28 so I looked into what was using my space and noticed the flatpak runtimes were taking significant space. I saw that I had three versions of the GNOME runtime and thought surely nothing was depending on the older one, so I proceeded and removed 3.24 which freed up between 400 and 500MB, a non trivial amount of disk space (especially on root partitions that have a tendency to be limited).

flatpak didn’t complain about me removing a dependency of something I had installed (which is another issue on its own) and offered to reinstall the runtime on next update, which is how I discovered that Recipes was still built against this version.

**Comment by bilelmoussaoui** [comment]
It now uses 3.34 https://github.com/flathub/org.gnome.Recipes/pull/12
